:sparkles: New Tabs UI
interest-protocol/interest-ui pull request #100
Opened 2023-11-15 22:41 UTC by KipandaJr

2023-11-16 01:22 UTC, okusindja commented on src/lib/components/tabs/stories/index.stories.tsx
> +    type: {
Remove comments

2023-11-16 01:23 UTC, okusindja commented on src/lib/components/tabs/stories/index.stories.tsx
> +    type: {
@KipandaJr

2023-11-16 07:30 UTC, KipandaJr commented on src/lib/components/tabs/stories/index.stories.tsx
> +    type: {
Solved

2023-11-16 12:19 UTC, MarioBatalha commented on src/lib/components/tabs/stories/index.stories.tsx
> -  //     control: { type: 'text' },
How about this code smells?

2023-11-16 12:25 UTC, MarioBatalha requested changes

2023-11-16 12:25 UTC, MarioBatalha commented on src/lib/components/tabs/stories/index.stories.tsx
> -  //   },
Remove commented code

2023-11-16 20:35 UTC, git-marcopitra requested changes
Stories for Square Tabs

2023-11-16 20:58 UTC, KipandaJr commented on src/lib/components/tabs/stories/index.stories.tsx
> -  //   },
i just remove this.

2023-11-18 21:32 UTC, git-marcopitra approved these changes

2023-11-18 21:32 UTC, merged