:sparkles: Adding new checkboxes
interest-protocol/interest-ui pull request #104
Opened 2023-11-17 07:25 UTC by KipandaJr

2023-11-17 17:43 UTC, MarioBatalha commented on src/lib/components/checkbox/index.tsx
> +          ? -1
You can put his between parentheses () to be more readable

2023-11-17 17:45 UTC, MarioBatalha commented on src/lib/components/checkbox/stories/index.stories.tsx
>  export const Normal: Story = {
Normal checkbox isn't working as expected, when I click on normal checkbox to enable or disabled it's work on default checkbox

2023-11-17 18:01 UTC, MarioBatalha requested changes

2023-11-17 18:01 UTC, MarioBatalha commented on src/lib/components/checkbox/stories/index.stories.tsx
> +export const NormalWithIndetermated: Story = {
Normal checkbox isn't working as expected, when I click on normal checkbox to enable or disabled it's work on default checkbox

2023-11-18 22:50 UTC, git-marcopitra approved these changes

2023-11-18 22:55 UTC, merged