:sparkles: Switch
interest-protocol/interest-ui pull request #11
Opened 2023-04-12 00:16 UTC by KipandaJr

2023-04-12 09:38 UTC, git-marcopitra requested changes

2023-04-12 09:38 UTC, git-marcopitra commented on src/lib/components/switch/switch.types.ts
> +  initialValue: boolean;
I it is a normal input, for sure, it has a default value, just use it

2023-04-12 09:38 UTC, git-marcopitra commented on src/lib/components/switch/index.tsx
> +  initialValue,
replace for `defaultValue`

2023-04-12 09:38 UTC, git-marcopitra commented on src/lib/components/switch/index.tsx
> +            bg: dark ? 'foreground' : 'background',
avoid handle the color using `dark`, only if it's unavoidable

2023-04-12 09:38 UTC, git-marcopitra commented on src/lib/components/switch/index.tsx
> +            bg: dark ? 'foreground' : 'background',
In this case, it can keep, but just be care with the next cases

2023-04-13 23:28 UTC, merged

2023-04-14 00:05 UTC, okusindja reviewed
Done ✅