:recycle: refactor: remake of info-card
interest-protocol/interest-ui pull request #116
Opened 2023-12-26 21:19 UTC by atilasousa

2023-12-26 22:11 UTC, KipandaJr requested changes
<img width="440" alt="image" src="https://github.com/interest-protocol/interest-ui/assets/34079870/02e64d99-ed2b-4bc7-8120-7781d978acd7">

the padding Y and X should be equal according figma

2023-12-26 22:11 UTC, KipandaJr commented on src/lib/components/info-card/index.tsx
> +      height="8.25rem"
try remove this `height` and put a `gap="l or m"` (according theme-space to 1rem)

2023-12-26 22:11 UTC, KipandaJr commented on src/lib/components/info-card/index.tsx
> +      width={width ?? '26.75rem'}
instead use `with` try put a `max-width`

2023-12-26 22:11 UTC, KipandaJr commented on src/lib/components/info-card/index.tsx
>        color={dark ? 'white' : 'onSurface'}
remove color `white` and put `lowestContainer` to white color

2023-12-26 22:11 UTC, KipandaJr commented on src/lib/components/info-card/index.tsx
> +          <MoneySignSVG maxHeight="1.5rem" maxWidth="1.5rem" width="100%" />
Icon should be a props, `ReactNode` prop

2023-12-26 22:11 UTC, KipandaJr commented on src/lib/components/info-card/info-card.types.ts
>    title: ReactNode;
put one props to icon like `icon: ReactNode`

2023-12-26 22:11 UTC, KipandaJr commented on src/lib/components/info-card/index.tsx
see when we put a custom `width`, i think we need a `min-width` ou put scroll bar when its so short, `Overflow-x` in this case. cuz when we put a so short value the card have a weird behavior

2024-01-02 22:15 UTC, MarioBatalha approved these changes

2024-01-03 18:08 UTC, KipandaJr commented on src/lib/components/info-card/info-card.types.ts
> +  icon?: ReactNode;
React Node Props need start capitalized

2024-01-03 20:41 UTC, git-marcopitra commented
<img width="465" alt="image" src="https://github.com/interest-protocol/interest-ui/assets/59171412/f1ba2685-af63-41e4-8b88-2538f4a07e2c">

Take a look at info card footer on Storybook

2024-01-03 20:43 UTC, git-marcopitra requested changes
See Antonio's changes

2024-01-16 17:58 UTC, git-marcopitra requested changes

2024-01-16 17:58 UTC, git-marcopitra commented on pnpm-lock.yaml
remove this file

2024-01-18 20:08 UTC, merged