:sparkles: charts component
interest-protocol/interest-ui pull request #119
Opened 2024-01-18 09:35 UTC by atilasousa

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206189181392434

2024-01-18 20:07 UTC, KipandaJr requested changes
<img width="420" alt="image" src="https://github.com/interest-protocol/interest-ui/assets/34079870/049ed8d3-fe34-4391-8213-7cc71109ff23">

- Check this bullets r weird

<img width="104" alt="image" src="https://github.com/interest-protocol/interest-ui/assets/34079870/90806f14-8a15-4c35-94c6-a4b9f5a67ff4">

- Check this line

<img width="262" alt="image" src="https://github.com/interest-protocol/interest-ui/assets/34079870/8eded811-ec0e-4761-ab1e-c0ac5ada33fa">

- On hover change the cursor and remove other stuff

2024-01-18 20:39 UTC, MarioBatalha approved these changes

2024-01-23 01:17 UTC, KipandaJr requested changes
plz check everything that i comment again

2024-01-25 19:05 UTC, KipandaJr requested changes

2024-01-25 19:05 UTC, KipandaJr commented on src/lib/components/charts/circle-chart/index.tsx
> +          wrapperStyle={{ top: '170px', bottom: 'unset' }}
change `px` to `rem`

2024-01-29 20:07 UTC, KipandaJr approved these changes

2024-01-30 00:05 UTC, git-marcopitra approved these changes

2024-01-30 00:05 UTC, merged