✨ Add progress indicator component
interest-protocol/interest-ui pull request #12
Opened 2023-04-12 13:17 UTC by okusindja

2023-04-12 15:02 UTC, git-marcopitra requested changes

2023-04-12 15:06 UTC, git-marcopitra commented
For Circle Progress, try to do something like a loading circle

2023-04-12 18:14 UTC, okusindja commented
> For Circle Progress, try to do something like a loading circle

I didn't understand what you want to say, can you please give me an example?

2023-04-12 21:13 UTC, okusindja commented
> > For Circle Progress, try to do something like a loading circle
> 
> I didn't understand what you want to say, can you please give me an example?

Done ✅

2023-04-13 21:18 UTC, git-marcopitra requested changes

2023-04-14 02:18 UTC, merged