:test_tube: test: new test in tooltip
interest-protocol/interest-ui pull request #158
Opened 2024-06-19 14:36 UTC by atilasousa

2024-06-19 16:30 UTC, MarioBatalha approved these changes

2024-07-15 20:16 UTC, KipandaJr requested changes
The test structure doesn't seem to meet our current development standards, since the creation of the test cases seems insufficient.

Your tests fail, so they can't pass that way.

2024-07-21 17:40 UTC, MarioBatalha requested changes
Is missing test for cursor pointer

2024-07-29 19:51 UTC, MarioBatalha approved these changes

2024-07-29 21:51 UTC, KipandaJr requested changes
- Check the role
- Check how u get the variables
- check ur your approach to picking up your children

2024-08-01 19:07 UTC, KipandaJr approved these changes

2024-08-01 19:07 UTC, merged