:test_tube: Add new textfield test
interest-protocol/interest-ui pull request #163
Opened 2024-07-01 23:10 UTC by MarioBatalha

2024-08-01 19:26 UTC, KipandaJr requested changes
- Check the point on aria-label

2024-08-12 19:23 UTC, KipandaJr requested changes
- Check if the value that u put on input is expected
- Check the description test

2024-08-13 19:06 UTC, KipandaJr requested changes

2024-08-13 19:06 UTC, KipandaJr commented on src/lib/components/text-field/stories/index.stories.tsx
> +      const inputValue = '0.123';
fake

2024-08-14 19:11 UTC, atilasousa requested changes

2024-08-14 19:11 UTC, atilasousa commented on src/lib/components/text-field/stories/index.stories.tsx
> +    await step('Testing textfield input', async () => {
it should be Testing Textfield structure

2024-08-14 19:11 UTC, atilasousa commented on src/lib/components/text-field/index.tsx
> +            aria-label="input"
Check this aria-label

2024-08-16 19:14 UTC, atilasousa approved these changes

2024-08-18 19:38 UTC, atilasousa approved these changes

2024-08-19 16:21 UTC, KipandaJr approved these changes

2024-08-19 16:21 UTC, merged