:test_tube: test: listitem
interest-protocol/interest-ui pull request #166
Opened 2024-07-11 18:43 UTC by atilasousa

2024-07-25 23:25 UTC, MarioBatalha requested changes

2024-07-25 23:25 UTC, MarioBatalha commented on src/lib/components/list-item/index.tsx
> +      role="listitem"
Please use camel case name convention

2024-07-31 17:39 UTC, MarioBatalha approved these changes

2024-07-31 20:23 UTC, KipandaJr approved these changes

2024-07-31 20:26 UTC, merged