:test_tube: test: new dropwn test
interest-protocol/interest-ui pull request #169
Opened 2024-07-29 19:21 UTC by atilasousa

2024-07-29 19:50 UTC, MarioBatalha approved these changes

2024-07-29 23:45 UTC, KipandaJr requested changes

2024-07-29 23:45 UTC, KipandaJr commented on src/lib/components/dropdown-button/stories/index.stories.tsx
> +    const textElements = button.getElementsByTagName('p');
Use toHaveStyle to search for these properties and make everything cleaner

2024-07-29 23:45 UTC, KipandaJr commented on src/lib/components/dropdown-button/stories/index.stories.tsx
> +    clearAllMocks();
Remove this, because dosent make difference

2024-07-29 23:45 UTC, KipandaJr commented on src/lib/components/dropdown-button/stories/index.stories.tsx
> +      const background = computedStyle.getPropertyValue('background');
Use toHaveStyle

2024-07-29 23:45 UTC, KipandaJr commented on src/lib/components/dropdown-button/stories/index.stories.tsx
> +        'It expects that the dropdown shadow is rgba(13, 16, 23, 0.04) 0px 2px 4px -2px, rgba(13, 16, 23, 0.12) 0px 4px 8px -2px'
you can simplify these titles so they don't get too big, you can just use the property and not the value

2024-07-31 19:46 UTC, KipandaJr approved these changes

2024-07-31 19:46 UTC, merged