🐛 Add new tokenfield
interest-protocol/interest-ui pull request #179
Opened 2024-08-01 22:21 UTC by MarioBatalha

2024-08-02 18:56 UTC, atilasousa approved these changes

2024-08-05 08:34 UTC, KipandaJr requested changes
- Solve the problem of the component re-rendering when entering information.
- Label tests missing (such as the text and its position)
- Missing interaction tests with button max and input change

2024-08-12 19:30 UTC, KipandaJr requested changes
- Check the clearAllMocks() 
- Check the type on input

2024-08-14 19:01 UTC, atilasousa approved these changes

2024-08-15 22:40 UTC, KipandaJr requested changes

2024-08-15 22:40 UTC, KipandaJr commented on src/lib/components/token-field/stories/index.stories.tsx
> +      });
Use the same approach that i suggest in Textfield

2024-08-20 23:39 UTC, closed without merging