Refactor/dropdown
interest-protocol/interest-ui pull request #181
Opened 2024-08-03 22:56 UTC by atilasousa

2024-08-05 00:10 UTC, KipandaJr requested changes

2024-08-05 00:10 UTC, KipandaJr commented on src/lib/components/dropdown-button/stories/index.stories.tsx
> +      ).toHaveTextContent('Option 2');
there seems to be no difference in the way you take the elements from your dropdown, and this doesn't validate the test

2024-08-05 00:10 UTC, KipandaJr commented on src/lib/components/dropdown-button/stories/index.stories.tsx
> +      ).toBe(6);
what is the need to test this?

2024-08-19 19:25 UTC, MarioBatalha reviewed
Check the icon color in dark mode

2024-08-20 19:16 UTC, MarioBatalha approved these changes

2024-08-20 22:16 UTC, KipandaJr approved these changes

2024-08-20 22:17 UTC, merged