Fix/button role
interest-protocol/interest-ui pull request #183
Opened 2024-08-08 15:00 UTC by atilasousa

2024-08-08 19:17 UTC, KipandaJr requested changes

2024-08-08 19:17 UTC, KipandaJr commented on src/lib/components/modal/stories/index.stories.tsx
> -        ).toHaveBeenCalled();
we need check if the button close is called when we click the button

2024-08-09 19:02 UTC, MarioBatalha approved these changes

2024-08-12 19:40 UTC, KipandaJr approved these changes

2024-08-12 19:40 UTC, merged