:recycle: refactor: adding border and new tests covers
interest-protocol/interest-ui pull request #184
Opened 2024-08-08 22:12 UTC by atilasousa

2024-08-09 19:05 UTC, MarioBatalha requested changes
I can't the border you applied

2024-08-14 19:12 UTC, MarioBatalha approved these changes

2024-08-14 19:18 UTC, MarioBatalha reviewed
Border should  cover the entire tooltip wrapper

2024-08-15 21:50 UTC, KipandaJr approved these changes

2024-08-15 21:51 UTC, merged