Refactor/charts
interest-protocol/interest-ui pull request #191
Opened 2024-08-29 21:10 UTC by atilasousa

2024-08-31 17:59 UTC, MarioBatalha reviewed
Charts doesn't look good in dark theme, except the first one.

2024-08-31 17:59 UTC, MarioBatalha commented on src/lib/components/charts/stories/charts.data.ts
>  export const CHARTS_DATA = [
Is missing types for this data

2024-09-01 21:08 UTC, MarioBatalha approved these changes

2024-09-01 23:03 UTC, KipandaJr requested changes
Line Chart Expected 
![image](https://github.com/user-attachments/assets/1e47ab42-1714-4bc2-811b-5ae94077a23f)

Line Chart that we have 
![image](https://github.com/user-attachments/assets/79970e10-ee92-4e9d-96f3-e0556bf2d237)

2024-09-03 19:08 UTC, KipandaJr requested changes

2024-09-03 19:08 UTC, KipandaJr commented on src/lib/components/charts/charts.types.ts
> +  lineType?: 'monotone';
dosent make sense this should be `lineType?: 'monotone' | <alternative value>`

2024-09-03 20:17 UTC, KipandaJr approved these changes

2024-09-03 20:18 UTC, merged